import mutations from './mutations';
import getters from './getters';
import actions from './actions';

const state = {
    Camera: [
        {
            id: "897568346",
            date: "2018-10-11",
            type: "camera",
            name: "IP-камера Xiaomi MiJia 360° Home Camera (версия PTZ)",
            price: "124 000",
            currency: "RUR",
            src_image: "/public/i/image/photo-1.jpg",
            href: "/products/Camera/IP-kamera_Xiaomi_MiJia_360_Home_Camera_(versiya PTZ)&897568346",
            presence: true,
            promotion: false,
            promotion_price: "",
            promotion_percent: "",
            stars: "3.5",
            comment_count: 10
        },
        {
            id: "345341235",
            date: "2018-10-11",
            type: "camera",
            name: "Зеркальный фотоаппарат Nikon Df Body Black",
            price: "17 200",
            currency: "RUR",
            src_image: "/public/i/image/photo-2.jpg",
            href: "/products/Camera/Zerkal'nyj_fotoapparat_Nikon_Df_Body_Black&345341235",
            presence: true,
            promotion: false,
            promotion_price: "",
            promotion_percent: "",
            stars: 3,
            comment_count: 3
        },
        {
            id: "078856755",
            date: "2018-10-11",
            type: "camera",
            name: "Зеркальный фотоаппарат Canon EOS 6D Kit EF 24-105mm IS STM",
            price: "31 000",
            currency: "RUR",
            src_image: "/public/i/image/photo-3.jpg",
            href: "/products/Camera/Zerkal'nyj_fotoapparat_Canon_EOS_6D_Kit_EF_24-105mm_IS_STM&078856755",
            presence: true,
            promotion: true,
            promotion_price: "38 700",
            promotion_percent: "20",
            stars: 5,
            comment_count: 2
        },
        {
            id: "756239423",
            date: "2018-10-11",
            type: "camera",
            name: "Зеркальный фотоаппарат Canon EOS 70D Kit 18-55 IS STM",
            price: "4 000",
            currency: "RUR",
            src_image: "/public/i/image/photo-4.jpg",
            href: "/products/Camera/Zerkal'nyj_fotoapparat_Canon_EOS_70D_Kit_18-55_IS_STM&756239423",
            presence: true,
            promotion: false,
            promotion_price: "",
            promotion_percent: "",
            stars: 4,
            comment_count: 1
        },
        {
            id: "78942345671",
            date: "2018-10-11",
            type: "camera",
            name: "Зеркальный фотоаппарат Nikon Df Body Black",
            price: "124 000",
            currency: "RUR",
            src_image: "/public/i/image/photo-5.jpg",
            href: "/products/Camera/Zerkal'nyj_fotoapparat_Nikon_Df_Body_Black&78942345671",
            presence: true,
            promotion: false,
            promotion_price: "",
            promotion_percent: "",
            stars: 4,
            comment_count: 5
        },
        {
            id: "89756867345346",
            date: "2018-10-11",
            type: "camera",
            name: "IP-камера Xiaomi MiJia 360° Home Camera (версия PTZ)",
            price: "",
            currency: "RUR",
            src_image: "/public/i/image/photo-1.jpg",
            href: "/products/Camera/IP-kamera_Xiaomi_MiJia_360_Home_Camera_(versiya PTZ)&89756867345346",
            presence: false,
            promotion: false,
            promotion_price: "",
            promotion_percent: "",
            stars: 4,
            comment_count: 10
        },
        {
            id: "3454234341235",
            date: "2018-10-11",
            type: "camera",
            name: "Зеркальный фотоаппарат Nikon Df Body Black",
            price: "17 200",
            currency: "RUR",
            src_image: "/public/i/image/photo-2.jpg",
            href: "/products/Camera/Zerkal'nyj_fotoapparat_Nikon_Df_Body_Black&3454234341235",
            presence: true,
            promotion: false,
            promotion_price: "",
            promotion_percent: "",
            stars: 3,
            comment_count: 3
        },
        {
            id: "07885657656755",
            date: "2018-10-11",
            type: "camera",
            name: "Зеркальный фотоаппарат Canon EOS 6D Kit EF 24-105mm IS STM",
            price: "31 000",
            currency: "RUR",
            src_image: "/public/i/image/photo-3.jpg",
            href: "/products/Camera/Zerkal'nyj_fotoapparat_Canon_EOS_6D_Kit_EF_24-105mm_IS_STM&07885657656755",
            presence: true,
            promotion: true,
            promotion_price: "38 700",
            promotion_percent: "20",
            stars: 5,
            comment_count: 2
        },
        {
            id: "756212339423",
            date: "2018-10-11",
            type: "camera",
            name: "Зеркальный фотоаппарат Canon EOS 70D Kit 18-55 IS STM",
            price: "4 000",
            currency: "RUR",
            src_image: "/public/i/image/photo-4.jpg",
            href: "/products/Camera/Zerkal'nyj_fotoapparat_Canon_EOS_70D_Kit_18-55_IS_STM&756212339423",
            presence: true,
            promotion: false,
            promotion_price: "",
            promotion_percent: "",
            stars: 4,
            comment_count: 1
        },
        {
            id: "78942978345671",
            date: "2018-10-11",
            type: "camera",
            name: "Зеркальный фотоаппарат Nikon Df Body Black",
            price: "124 000",
            currency: "RUR",
            src_image: "/public/i/image/photo-5.jpg",
            href: "/products/Camera/Zerkal'nyj_fotoapparat_Nikon_Df_Body_Black&78942978345671",
            presence: true,
            promotion: false,
            promotion_price: "",
            promotion_percent: "",
            stars: 4,
            comment_count: 5
        },
    ]
};

export default {
  	namespaced: true,
  	state,
  	mutations,
  	getters,
  	actions,
};